### ISSUE TITLE
Not able to use with jruby

### ISSUE THREAD

**Issue by sebin** [romanbsd/fast-stemmer#12]
I am facing an error while installing this gem under jruby 9.0.4.0 (2.2.2)

NotImplementedError: C extensions are not supported

**Comment by timkaechele** [comment]
That is a completely normal behaviour. The JRuby implementation does not support C extensions. Because of these circumstances you have two options: you can use another ruby stemming gem that is written solely in ruby or you can choose one of the many Java stemming implementations. By using JRuby you can access every Java Library within Ruby. 

I am not familiar with the stemming library landscape in the java world, but a quick search brought up the [stanford natural language processing library ](https://github.com/stanfordnlp/CoreNLP) which looks like a fairly extensive solution to natural language processing problems. 

I hope I was able top help you.
